#!/bin/bash

PATH="/opt/java/jdk/active/bin:$PATH"

JAVA_HOME_DIR="/opt/java/jdk/active"
if [ -d "${JAVA_HOME_DIR}" ] ; then
	JAVA_HOME="${JAVA_HOME_DIR}"
fi

ANDROID_HOME_DIR="/opt/android/sdk"
if [ -d "${ANDROID_HOME_DIR}" ] ; then
	ANDROID_HOME="${ANDROID_HOME_DIR}"
fi

GDX_SETUP_JAR="/opt/development/share/lib/gdx-setup.jar"

if [ ! -f "${GDX_SETUP_JAR}" ] ; then
	echo "Error: failed to locate gdx-setup.jar!" >&2
	exit 1
fi

exec java -jar "${GDX_SETUP_JAR}" $*

#
# End Of File
#
